// data/anime-shows.ts
export const animeShows = [
  // === SHONEN ===
  {
    id: 1,
    name: "Attack on Titan",
    query: "Warhammer Titan Theme - Attack on Titan OST",
    year: 2013,
    genre: "Action",
    youtubeId: "JFr_quDd5aQ",
  },
  {
    id: 2,
    name: "Demon Slayer",
    query: "Demon Slayer: Infinity Castle OST ",
    year: 2019,
    genre: "Action",
    youtubeId: "JrUX63FleCw",
  },
  {
    id: 3,
    name: "My Hero Academia",
    query: "My Hero Academia UST - Kyoui to no Koubou (No Drums)",
    year: 2016,
    genre: "Action",
    youtubeId: "MFTlL0xFqp8",
  },
  {
    id: 4,
    name: "One Piece",
    query: "One Piece Soundtrack - Gold And Oden HD",
    year: 1999,
    genre: "Adventure",
    youtubeId: "6FscTa_Nqwo",
  },
  {
    id: 5,
    name: "Naruto Shippuden",
    query: "Naruto Shippuden OST - Uchiha Madara Theme Song",
    year: 2002,
    genre: "Action",
    youtubeId: "cJfNz8csSTk",
  },
  {
    id: 6,
    name: "Bleach",
    query: "Nightcore - Bleach OST - Stand up, be Strong",
    year: 2004,
    genre: "Action",
    youtubeId: "Cp0mAzF-UKc",
  },
  {
    id: 7,
    name: "Dragon Ball Z",
    query: "Dragon Ball Z - BP∞ Battle Point Unlimited",
    year: 1989,
    genre: "Action",
    youtubeId: "eMYt9sGOcTU",
  },
  {
    id: 8,
    name: "Fullmetal Alchemist Brotherhood",
    query: "Trisha's Lullaby",
    year: 2003,
    genre: "Action",
    youtubeId: "hBkh7DRNqw8",
  },
  {
    id: 9,
    name: "Hunter x Hunter",
    query: "Ansatsu Ikka no Yakata",
    year: 2011,
    genre: "Adventure",
    youtubeId: "riufO6yAgHo",
  },
  {
    id: 10,
    name: "Jujutsu Kaisen",
    query: "Jujutsu Kaisen OST - Yuuji's Rage (One’s Innermost Thoughts)",
    year: 2020,
    genre: "Action",
    youtubeId: "bkpX2kfHprc",
  },

  // === SEINEN ===
  {
    id: 11,
    name: "Death Note",
    query: 'Death Note OST I - "Taikutsu",',
    year: 2006,
    genre: "Thriller",
    youtubeId: "hWX9Bvm-Cd4",
  },
  {
    id: 12,
    name: "Tokyo Ghoul",
    query: "Tokyo Ghoul - Ending | Saints",
    year: 2014,
    genre: "Horror",
    youtubeId: "kSkSvK6Zx_I",
  },
  {
    id: 13,
    name: "Parasyte",
    query: "[OST] Parasyte - I AM",
    year: 2014,
    genre: "Horror",
    youtubeId: "vxLbI80RdYs",
  },
  {
    id: 15,
    name: "Psycho-Pass",
    query: "「PSYCHO-PASS サイコパス」2クール目OPテーマ",
    year: 2012,
    genre: "Sci-Fi",
    youtubeId: "SJ-aUXmJM8Q",
  },
  {
    id: 16,
    name: "Monster",
    query: "Monster OST - Drift",
    year: 2004,
    genre: "Thriller",
    youtubeId: "I0usR-H9y7A",
  },
  {
    id: 18,
    name: "Vinland Saga",
    query:
      "STILL BLADE - Vinland Saga OST (ヴィンランド・サガ ) Epic Battle Orchestral Cover",
    year: 2019,
    genre: "Action",
    youtubeId: "MY8mMvHfUTE",
  },
  {
    id: 20,
    name: "One Punch Man",
    query: "「Creditless」One Punch Man OP / Opening 2「UHD 60FPS」",
    year: 2015,
    genre: "Action",
    youtubeId: "OvgBFgLUyC8",
  },

  // === ROMANCE / SLICE OF LIFE ===
  {
    id: 21,
    name: "Your Lie in April",
    query: "your lie in april opening hikaru nara",
    year: 2014,
    genre: "Romance",
    youtubeId: "fWRPihlt2ho",
  },
  {
    id: 22,
    name: "Toradora",
    query: "toradora opening pre parade",
    year: 2008,
    genre: "Romance",
    youtubeId: "ylPEBnmRRxQ",
  },
  {
    id: 23,
    name: "Clannad",
    query: "clannad opening megumeru",
    year: 2007,
    genre: "Drama",
    youtubeId: "zgB0Y_BUvFE",
  },
  {
    id: 26,
    name: "Fruits Basket",
    query: "Fruits Basket Season 2 Ending 2 - 『Eden』- TV size",
    year: 2019,
    genre: "Romance",
    youtubeId: "TKBlq6ox7Ys",
  },
  {
    id: 28,
    name: "Horimiya",
    query: "horimiya opening iro kousui",
    year: 2021,
    genre: "Romance",
    youtubeId: "7DpONAPM3Zw",
  },
  {
    id: 30,
    name: "Violet Evergarden",
    query: "violet evergarden opening sincerely",
    year: 2018,
    genre: "Drama",
    youtubeId: "ZAKuyZEyZjY",
  },

  // === ISEKAI / FANTASY ===
  {
    id: 31,
    name: "Sword Art Online",
    query: "Gleam Eyes OST (sword art online) We have to defeat it.",
    year: 2012,
    genre: "Isekai",
    youtubeId: "1h994kmCrpI",
  },
  {
    id: 32,
    name: "Re:Zero",
    query: "Re:ZERO -Starting Life in Another World- Season 3 Opening",
    year: 2016,
    genre: "Isekai",
    youtubeId: "hCxZx7uHO1I",
  },
  {
    id: 33,
    name: "Overlord",
    query: "Overlord III Opening | VORACITY",
    year: 2015,
    genre: "Isekai",
    youtubeId: "vci9YwpFFcA",
  },
  {
    id: 34,
    name: "Konosuba",
    query: "konosuba opening fantastic dreamer",
    year: 2016,
    genre: "Comedy",
    youtubeId: "fpG3BPNQepY",
  },
  {
    id: 35,
    name: "That Time I Got Reincarnated as a Slime",
    query: "slime opening nameless story",
    year: 2018,
    genre: "Isekai",
    youtubeId: "ZhvUomsfG8o",
  },
  {
    id: 36,
    name: "The Rising of the Shield Hero op saison 3",
    query: "The Rising of the Shield Hero Season 3 Opening ",
    year: 2019,
    genre: "Isekai",
    youtubeId: "-ZGrwqpwSQs",
  },
  {
    id: 37,
    name: "Mushoku Tensei",
    query: "mushoku tensei opening tabibito no uta",
    year: 2021,
    genre: "Isekai",
    youtubeId: "QG8UZUahRbI",
  },
  {
    id: 38,
    name: "No Game No Life",
    query: "Anime de Japan - All Of You Is All Of Me Theme (No Game No Life)",
    year: 2014,
    genre: "Isekai",
    youtubeId: "hoEVwicbZTk",
  },
  {
    id: 39,
    name: "Log Horizon",
    query: "log horizon opening database",
    year: 2013,
    genre: "Isekai",
    youtubeId: "eW6sEkTGbUc",
  },
  {
    id: 40,
    name: "Grimgar",
    query: "grimgar opening knew day",
    year: 2016,
    genre: "Isekai",
    youtubeId: "sO4DEqVzlD4",
  },

  // === SPORTS ===
  {
    id: 41,
    name: "Haikyuu",
    query: "Haikyuu!! OST - Omnivorous",
    year: 2014,
    genre: "Sports",
    youtubeId: "isy3ikkIpqw",
  },
  {
    id: 42,
    name: "Kuroko no Basket",
    query: "Kuroko no Basket Season 2 - OST 05 Imminence",
    year: 2012,
    genre: "Sports",
    youtubeId: "aeZKSOYh5KE",
  },
  {
    id: 43,
    name: "Slam Dunk",
    query: "slam dunk opening kimi ga suki da to sakebitai",
    year: 1993,
    genre: "Sports",
    youtubeId: "YhkQvv6BMEs",
  },
  {
    id: 45,
    name: "Yuri on Ice",
    query:
      "YURI!!! on ICE Ending Full『Wataru Hatano - You Only Live Once』【ENG Sub】",
    year: 2016,
    genre: "Sports",
    youtubeId: "FjFGBrPIJsk",
  },
  {
    id: 46,
    name: "Hajime no Ippo",
    query: "Hajime No Ippo OST 20 - Arayashiki [HD]",
    year: 2000,
    genre: "Sports",
    youtubeId: "lX8mthPC5vY",
  },
  {
    id: 47,
    name: "Ace of Diamond",
    query: "ace of diamond opening go exceed",
    year: 2013,
    genre: "Sports",
    youtubeId: "ViBE_zYivNc",
  },
  {
    id: 48,
    name: "Run with the Wind",
    query: "run with the wind opening catch up latent",
    year: 2018,
    genre: "Sports",
    youtubeId: "PxQI5f2Stbg",
  },
  {
    id: 50,
    name: "Blue Lock",
    query: "BLUELOCK Original Soundtrack : Despair",
    year: 2022,
    genre: "Sports",
    youtubeId: "WY1LPooUeBI",
  },

  // === MECHA / SCI-FI ===
  {
    id: 51,
    name: "Neon Genesis Evangelion",
    query: "Kokoro Yo Genshi ni Modoru - Evangelion Alternate Opening 2",
    year: 1995,
    genre: "Mecha",
    youtubeId: "V1MdqanqJ5o",
  },
  {
    id: 54,
    name: "Cowboy Bebop",
    query: "Cowboy Bebop - The Real Folk Blues générique de fin",
    year: 1998,
    genre: "Sci-Fi",
    youtubeId: "eyI635o2pmk",
  },
  {
    id: 55,
    name: "Gundam Wing",
    query: "gundam wing opening",
    year: 1979,
    genre: "Mecha",
    youtubeId: "oNJ4aBoRipg",
  },
  {
    id: 56,
    name: "Darling in the Franxx",
    query: "darling in the franxx opening kiss of death",
    year: 2018,
    genre: "Mecha",
    youtubeId: "A4kLcDWBYcQ",
  },
  {
    id: 58,
    name: "Aldnoah.Zero",
    query: "【ALDNOAH ZERO】-OPENING 2 HD アルドノアゼロ OP 2",
    year: 2014,
    genre: "Mecha",
    youtubeId: "txiYc9FEUzY",
  },
  {
    id: 59,
    name: "Knights of Sidonia",
    query: "knights of sidonia opening sidonia",
    year: 2014,
    genre: "Mecha",
    youtubeId: "G_zn1a-dOvg",
  },
  {
    id: 60,
    name: "SSSS.Gridman",
    query: "gridman opening union",
    year: 2018,
    genre: "Mecha",
    youtubeId: "0PnikGsbjJM",
  },

  // === CLASSIQUES / NOSTALGIE ===
  {
    id: 61,
    name: "Sailor Moon",
    query: "sailor moon opening moonlight densetsu",
    year: 1992,
    genre: "Magical Girl",
    youtubeId: "R-DHOG6c2V8",
  },
  {
    id: 62,
    name: "Pokemon",
    query: "pokemon theme song",
    year: 1997,
    genre: "Adventure",
    youtubeId: "JuYeHPFR3f0",
  },
  {
    id: 63,
    name: "Yu-Gi-Oh",
    query: "yugioh opening 5 OVERLAP",
    year: 2000,
    genre: "Adventure",
    youtubeId: "o_Z0AhbSQxo",
  },
  {
    id: 64,
    name: "Digimon",
    query: "digimon opening butterfly",
    year: 1999,
    genre: "Adventure",
    youtubeId: "jB7ecG_12x8",
  },
  {
    id: 65,
    name: "Inuyasha",
    query: "inuyasha opening change the world",
    year: 2000,
    genre: "Fantasy",
    youtubeId: "BbHsd4PAME0",
  },
  {
    id: 66,
    name: "Cardcaptor Sakura",
    query: "Sakura Chasseuse de Cartes - No Nagging Anymore",
    year: 1998,
    genre: "Magical Girl",
    youtubeId: "zzIUgOVGYCs",
  },
  {
    id: 67,
    name: "Rurouni Kenshin",
    query: "rurouni kenshin opening sobakasu",
    year: 1996,
    genre: "Action",
    youtubeId: "0DBkXcDU270",
  },
  {
    id: 68,
    name: "Trigun",
    query: "trigun opening h t",
    year: 1998,
    genre: "Action",
    youtubeId: "4OxFSy8G5wk",
  },
  {
    id: 69,
    name: "Outlaw Star",
    query: "outlaw star opening through the night",
    year: 1998,
    genre: "Sci-Fi",
    youtubeId: "dAMCYV8iQNg",
  },
  {
    id: 70,
    name: "Ghost in the Shell",
    query:
      "Rise - Origa (Ghost in the Shell: Stand Alone Complex 2nd GIG OP FULL) HQ",
    year: 2002,
    genre: "Sci-Fi",
    youtubeId: "sJqe5clCBTI",
  },

  // === RÉCENTS / POPULAIRES ===
  {
    id: 71,
    name: "Chainsaw Man",
    query: "chainsaw man opening kick back",
    year: 2022,
    genre: "Action",
    youtubeId: "dFlDRhvM4L0",
  },
  {
    id: 73,
    name: "Cyberpunk Edgerunners",
    query: "Cyberpunk: Edgerunners - Ending 【Let You Down】 4K / UHD | CC",
    year: 2022,
    genre: "Sci-Fi",
    youtubeId: "jzmHj-u5JxQ",
  },
  {
    id: 74,
    name: "Bocchi the Rock",
    query: "bocchi the rock opening seishun complex",
    year: 2022,
    genre: "Music",
    youtubeId: "dlSbEP4V-gI",
  },
  {
    id: 75,
    name: "Lycoris Recoil",
    query: "lycoris recoil opening alive",
    year: 2022,
    genre: "Action",
    youtubeId: "6pWwVrVUsGo",
  },
  {
    id: 76,
    name: "Oshi No Ko - Ending 1",
    query: "Oshi No Ko - Ending 1 (Mephisto) | 4K UHD Creditless | Subtitles",
    year: 2023,
    genre: "Drama",
    youtubeId: "ZRtdQ81jPUQ",
  },
  {
    id: 77,
    name: "Frieren",
    query: "Dragon Smasher",
    year: 2023,
    genre: "Fantasy",
    youtubeId: "lrBUdDDHflU",
  },
  {
    id: 78,
    name: "Mashle",
    query: "MASHLE: MAGIC AND MUSCLES The Divine Visionary Candidate Exam Arc",
    year: 2023,
    genre: "Comedy",
    youtubeId: "FvCV9KXNKLY",
  },
  {
    id: 79,
    name: "Hell's Paradise",
    query: "hells paradise opening work",
    year: 2023,
    genre: "Action",
    youtubeId: "04WuoQMhhxw",
  },
  {
    id: 80,
    name: "The Dangers in My Heart",
    query: "dangers in my heart opening chime",
    year: 2023,
    genre: "Romance",
    youtubeId: "i3r4geiaMLs",
  },

  // === HORREUR / THRILLER ===
  {
    id: 82,
    name: "Elfen Lied",
    query: "elfen lied opening lilium",
    year: 2004,
    genre: "Horror",
    youtubeId: "f3KzmVblyHw",
  },
  {
    id: 83,
    name: "Higurashi",
    query: "higurashi opening higurashi no naku koro ni",
    year: 2006,
    genre: "Horror",
    youtubeId: "XgWkIrFQQE0",
  },
  {
    id: 84,
    name: "The Promised Neverland",
    query: "Isabella's Lullaby (vocal and mandolin ver.)",
    year: 2019,
    genre: "Thriller",
    youtubeId: "a2DWZeYfoCQ",
  },
  {
    id: 85,
    name: "Mirai Nikki",
    query: "mirai nikki opening kuusou mesorogiwi",
    year: 2011,
    genre: "Thriller",
    youtubeId: "ZZvJY7_gyfw",
  },
  {
    id: 86,
    name: "Terror in Resonance",
    query: "terror in resonance opening trigger",
    year: 2014,
    genre: "Thriller",
    youtubeId: "g1ARRcK4LVs",
  },
  {
    id: 87,
    name: "Corpse Party",
    query: "corpse party opening shangri-la",
    year: 2013,
    genre: "Horror",
    youtubeId: "wiZ_4Qr9jL4",
  },
  {
    id: 88,
    name: "Shiki",
    query: "shiki opening kuchizuke",
    year: 2010,
    genre: "Horror",
    youtubeId: "iKNnJS9lpFA",
  },
  {
    id: 89,
    name: "Hell Girl",
    query: "hell girl opening sakasama no chou",
    year: 2005,
    genre: "Horror",
    youtubeId: "Ft1D1coUmOM",
  },
  {
    id: 90,
    name: "Deadman Wonderland",
    query: "deadman wonderland opening one reason",
    year: 2011,
    genre: "Action",
    youtubeId: "2pZ-UpjtlXY",
  },

  // === DIVERS ===
  {
    id: 92,
    name: "Dr. Stone",
    query: "'A Dogfight Theme'『ドクターストーン』Dr. Stone S4 EP10 OST Cover",
    year: 2019,
    genre: "Sci-Fi",
    youtubeId: "3s6odgnJv6c",
  },
  {
    id: 93,
    name: "The Disastrous Life of Saiki K",
    query: "saiki k opening seishun wa zankoku janai",
    year: 2016,
    genre: "Comedy",
    youtubeId: "4GNTfA-seHY",
  },
  {
    id: 94,
    name: "Assassination Classroom",
    query: "assassination classroom opening seishun satsubatsuron",
    year: 2015,
    genre: "Action",
    youtubeId: "A41jCFkGiX0",
  },
  {
    id: 95,
    name: "Black Clover",
    query: "Black Clover OST - 05 -『Pentagram』",
    year: 2017,
    genre: "Action",
    youtubeId: "IWh5yfdHGOw",
  },
  {
    id: 96,
    name: "Fire Force",
    query: "fire force opening inferno",
    year: 2019,
    genre: "Action",
    youtubeId: "JBqxVX_LXvk",
  },
  {
    id: 97,
    name: "Dorohedoro",
    query: "dorohedoro opening welcome to chaos",
    year: 2020,
    genre: "Dark Fantasy",
    youtubeId: "BK0tDxrzUOc",
  },
  {
    id: 98,
    name: "Made in Abyss",
    query:
      "Hanezeve Caradhina (ft.Takeshi Saito) | Made in Abyss OST [ Lyrics ]",
    year: 2017,
    genre: "Adventure",
    youtubeId: "sFzDQ2OjFko",
  },
  {
    id: 99,
    name: "The Ancient Magus Bride",
    query: "ancient magus bride opening here",
    year: 2017,
    genre: "Fantasy",
    youtubeId: "KuZbmLLv1vM",
  },
  {
    id: 100,
    name: "Noragami",
    query: "noragami opening goya no machiawase",
    year: 2014,
    genre: "Action",
    youtubeId: "gWCnKoEgfP0",
  },
  {
    id: 101,
    name: "Gundam 00",
    query: "gundam 00 Fight ost",
    year: 2007,
    genre: "Mecha",
    youtubeId: "gM_xBLjtIH0",
  },
  {
    id: 103,
    name: "Hellsing Ultimate",
    query: "gradus vita",
    year: 2006,
    genre: "Action",
    youtubeId: "1d9hMAxKJ5Q",
  },
  {
    id: 104,
    name: "Serial Experiments Lain",
    query: "Serial Experiments Lain Soundtrack: 06 Working Man's Theme",
    year: 1998,
    genre: "Sci-Fi",
    youtubeId: "nTNI8DGAKlI",
  },
  {
    id: 105,
    name: "Akira",
    query: "akira ost kaneda",
    year: 1988,
    genre: "Sci-Fi",
    youtubeId: "Nja0Obgg2gU",
  },
  {
    id: 106,
    name: "Patlabor",
    query: "patlabor opening",
    year: 1989,
    genre: "Mecha",
    youtubeId: "Z9UtUzjUA5Q",
  },
  {
    id: 108,
    name: "Gunbuster",
    query: "gunbuster opening active heart",
    year: 1988,
    genre: "Mecha",
    youtubeId: "ZLhPBQpXafY",
  },
  {
    id: 109,
    name: "Macross",
    query: "macross opening",
    year: 1982,
    genre: "Mecha",
    youtubeId: "I4aQQBLokNo",
  },

  // === SEINEN / ACTION ===
  {
    id: 111,
    name: "Terra Formars",
    query: "terraformars opening",
    year: 2014,
    genre: "Action",
    youtubeId: "QW7HU71YRkg",
  },
  {
    id: 112,
    name: "Kengan Ashura",
    query: "Kengan Ashura Soundtrack - The Animal Fighter",
    year: 2019,
    genre: "Action",
    youtubeId: "7-UvccSXnwc",
  },
  {
    id: 113,
    name: "Kakegurui",
    query: "Kakegurui OST - High Strung",
    year: 2017,
    genre: "Thriller",
    youtubeId: "o4DuWZk9lKo",
  },
  {
    id: 114,
    name: "Golgo 13",
    query: "golgo 13 opening",
    year: 1983,
    genre: "Action",
    youtubeId: "pu8COKiheGo",
  },
  {
    id: 115,
    name: "City Hunter",
    query: "city hunter opening get wild",
    year: 1987,
    genre: "Action",
    youtubeId: "zhLdgee_EXk",
  },
  {
    id: 116,
    name: "Space Cobra",
    query: "space cobra opening",
    year: 1982,
    genre: "Sci-Fi",
    youtubeId: "dt6XXfcdVY0",
  },
  {
    id: 118,
    name: "Dragon Ball Super",
    query:
      "Dragon Ball Super OST - Vegeta’s New Form (Original SoundTrack) Quality HD",
    year: 2018,
    genre: "Action",
    youtubeId: "du_SYMFfbG4",
  },
  {
    id: 119,
    name: "Captain Tsubasa",
    query: 'Captain Tsubasa 1983 Original Soundtrack Misugi Jun"',
    year: 1983,
    genre: "Sports",
    youtubeId: "eAXYyC3TrdM",
  },
  {
    id: 120,
    name: "Hokuto no Ken",
    query:
      "Fist of the North Star - Opening 1 v1 【Ai wo Torimodose!!】 4K / UHD Creditless | CC",
    year: 1984,
    genre: "Action",
    youtubeId: "pRFxpHSNxkA",
  },
  {
    id: 121,
    name: "Saint Seiya",
    query: "Saint Seiya Opening 2 - Soldier Dream (Asgard Arc)",
    year: 1986,
    genre: "Action",
    youtubeId: "JUJP5eAxcIA",
  },
  {
    id: 122,
    name: "Cats Eye",
    query: "Cat's Eye Anime Intro Opening Theme HD",
    year: 1986,
    genre: "Action",
    youtubeId: "qcqQIt-dF-E",
  },
  {
    id: 123,
    name: "Dandadan",
    query: "DAN DA DAN - Opening | Otonoke de Creepy Nuts",
    year: 1986,
    genre: "Action",
    youtubeId: "qPdPjWkJZF8",
  },
  {
    id: 124,
    name: "Black Lagoon",
    query: "black lagoon opening red fraction",
    year: 2006,
    genre: "Action",
    youtubeId: "dWfxcRj39tg",
  },
  {
    id: 125,
    name: "Claymore",
    query: "claymore opening ration blue",
    year: 2007,
    genre: "Dark Fantasy",
    youtubeId: "dbj9Yjskco0",
  },
  {
    id: 126,
    name: "Ergo Proxy",
    query: "ergo proxy opening kyshiki",
    year: 2006,
    genre: "Sci-Fi",
    youtubeId: "oAXrRWLKzko",
  },
  {
    id: 127,
    name: "Texhnolyze",
    query: "texhnolyze opening guardian angel",
    year: 2003,
    genre: "Sci-Fi",
    youtubeId: "u3SzOzm8lmo",
  },
  {
    id: 128,
    name: "Erased",
    query: "erased opening re re",
    year: 2016,
    genre: "Thriller",
    youtubeId: "fodAJ-1dN3I",
  },
  {
    id: 129,
    name: "Tokyo Revengers",
    query: "tokyo revengers opening cry baby",
    year: 2021,
    genre: "Action",
    youtubeId: "O1bhZgkC4Gw",
  },
  {
    id: 130,
    name: "Gantz",
    query: "gantz opening super shooter",
    year: 2004,
    genre: "Horror",
    youtubeId: "SJ5ICtGn6u8",
  },
  {
    id: 131,
    name: "Soul Eater",
    query: "soul eater opening resonance",
    year: 2008,
    genre: "Action",
    youtubeId: "zzJ8U8OtEsE",
  },
  {
    id: 132,
    name: "Blue Exorcist",
    query: "「Creditless」Blue Exorcist OP / Opening 1「UHD 60FPS",
    year: 2011,
    genre: "Action",
    youtubeId: "s99s4VCtCP8",
  },
  {
    id: 133,
    name: "Magi",
    query: "Magi op 1 - creditless [HD]",
    year: 2012,
    genre: "Adventure",
    youtubeId: "GPKqy_kWCAo",
  },
  {
    id: 134,
    name: "Akame ga Kill",
    query: "akame ga kill opening skyreach",
    year: 2014,
    genre: "Action",
    youtubeId: "mAzFWd5WqOg",
  },
  {
    id: 135,
    name: "Seraph of the End",
    query: "owari no seraph opening x.u",
    year: 2015,
    genre: "Action",
    youtubeId: "aNgT6MxOURQ",
  },
  {
    id: 136,
    name: "Beyond the Boundary",
    query: "Beyond the Boundary - Opening",
    year: 2000,
    genre: "Action",
    youtubeId: "w1_XSFqfR74",
  },
  {
    id: 137,
    name: "Megalobox",
    query: "megalobox opening bite",
    year: 2018,
    genre: "Sports",
    youtubeId: "ByMrJy5p7q8",
  },
  {
    id: 138,
    name: "Tower of God",
    query: "tower of god opening top",
    year: 2020,
    genre: "Fantasy",
    youtubeId: "apII5VFTce0",
  },
  {
    id: 139,
    name: "Kaiju No. 8",
    query: "「Creditless」Kaiju No. 8 ED / Ending 2「UHD 60FPS」",
    year: 2024,
    genre: "Action",
    youtubeId: "koC2855Cdf8",
  },
  {
    id: 140,
    name: "Katekyo Hitman Reborn!",
    query: "Katekyo Hitman Reborn! OP 8 - Listen to the Stereo!!",
    year: 2006,
    genre: "Action",
    youtubeId: "I8uwTNmglrQ",
  },
  {
    id: 141,
    name: "Magical Doremi",
    query: "Magical Doremi - Générique saison 3 (Qualité DVD jp)",
    year: 2002,
    genre: "Action",
    youtubeId: "WazT_uV9L2o",
  },
  {
    id: 142,
    name: "Jormungand",
    query: "jormungand opening borderline",
    year: 2012,
    genre: "Action",
    youtubeId: "uDhEtUl7U-A",
  },
  {
    id: 143,
    name: "Dragon Ball GT",
    query:
      "Dragon Ball GT - Ending 2 (Don't you see!) | 4K UHD Creditless | Subtitles",
    year: 2003,
    genre: "Action",
    youtubeId: "SYfid5jok1M",
  },
  {
    id: 144,
    name: "Fate/Zero",
    query: "「Creditless」Fate/Zero OP / Opening 1「UHD 60FPS」",
    year: 2011,
    genre: "Action",
    youtubeId: "t1Wkgj7mntM",
  },
  {
    id: 145,
    name: "Baki 2018",
    query: "Baki (2018) | Opening 2 | [1080p] 60FPS",
    year: 2011,
    genre: "Action",
    youtubeId: "jdlu3cjSfb0",
  },
  {
    id: 146,
    name: "Seven Deadly Sins",
    query:
      "The Seven Deadly Sins Opening 1 - Passionate Spectrum | Creditless | 4K | English/Romaji Subtitles",
    year: 2014,
    genre: "Action",
    youtubeId: "MHsp-KkGo_g",
  },
  {
    id: 147,
    name: "Solo Levening",
    query: "「Creditless」Solo Leveling OP / Opening 2「UHD 60FPS」",
    year: 2024,
    genre: "Action",
    youtubeId: "vXLFNFvdcHg",
  },
  {
    id: 149,
    name: "One piece",
    query: "One piece Opening 13",
    year: 2007,
    genre: "Thriller",
    youtubeId: "hJgJTTIbMDI",
  },

  {
    id: 150,
    name: "Bleach",
    query: "Bleach op 13",
    year: 2007,
    genre: "Thriller",
    youtubeId: "5emM3JGI5JA",
  },
  {
    id: 152,
    name: "Fairy Tail",
    query: "Fairy Tail OP 1 - Gakuen no Yoru",
    year: 2007,
    genre: "Thriller",
    youtubeId: "o5pBXJLwz6U",
  },
  {
    id: 153,
    name: "Nanatsu no Taizai",
    query: "nanatsu no taizai",
    year: 2007,
    genre: "Thriller",
    youtubeId: "a4IiEX7ya-E",
  },
  {
    id: 154,
    name: "MGS4",
    query: "Metal Gear Solid 4",
    year: 2007,
    genre: "Thriller",
    youtubeId: "1xROQUdmP3U",
  },
  {
    id: 155,
    name: "fullmetal alchemist",
    query: "fullmetal alchemist opening 4",
    year: 2007,
    genre: "Thriller",
    youtubeId: "oPg1J79sgkQ",
  },
  {
    id: 156,
    name: "Kill la kill",
    query: "kill la kill opening 1",
    year: 2007,
    genre: "Thriller",
    youtubeId: "9_5LhZ7pQpM",
  },
  {
    id: 158,
    name: "Kenshin nvx",
    query: "Kenshin",
    year: 2007,
    genre: "Thriller",
    youtubeId: "03KqrRhvjw4",
  },
  {
    id: 159,
    name: "city hunter",
    query: "city hunter",
    year: 2007,
    genre: "Thriller",
    youtubeId: "FkiDM_xx-oA",
  },
  {
    id: 160,
    name: "fate ubw",
    query: "Fate Stay Night Ending 24 (Kimi to no Ashita)",
    year: 2007,
    genre: "Thriller",
    youtubeId: "JiOHxtgqgnM",
  },
  {
    id: 161,
    name: "spy family op 3",
    query: "spy family op 3",
    year: 2007,
    genre: "Thriller",
    youtubeId: "PcmmU4aEQu0",
  },
  {
    id: 170,
    name: "Kingdom",
    query:
      "Kingdom  Kingdom Season 4 Ending / ED 9 Full Lyrics Sub Español ( Genyou by Haku )",
    year: 2012,
    genre: "Action",
    youtubeId: "JLlEgc5Ghrs",
  },
];
