// data/anime-shows.ts
export const animeShows = [
  // === SHONEN ===
  {
    id: 1,
    name: "Attack on Titan",
    query: "Warhammer Titan Theme - Attack on Titan OST",
    year: 2013,
    genre: "Action",
    youtubeId: "AZEehl_G7KY",
  },
  {
    id: 2,
    name: "Demon Slayer",
    query: "Demon Slayer: Infinity Castle OST ",
    year: 2019,
    genre: "Action",
    youtubeId: "JrUX63FleCw",
  },
  {
    id: 3,
    name: "My Hero Academia",
    query: "Bakugo VS All For One",
    year: 2016,
    genre: "Action",
    youtubeId: "hS-6rFdT1JU",
  },
  {
    id: 4,
    name: "One Piece",
    query: "One Piece OST - Mother Sea",
    year: 1999,
    genre: "Adventure",
    youtubeId: "o231fOo8cNg",
  },
  {
    id: 5,
    name: "Naruto Shippuden",
    query: "Naruto Shippuden OST - Uchiha Madara Theme Song",
    year: 2002,
    genre: "Action",
    youtubeId: "cJfNz8csSTk",
  },
  {
    id: 6,
    name: "Bleach",
    query: "Treachery - Sosuke Aizen's Theme",
    year: 2004,
    genre: "Action",
    youtubeId: "bWAVOlfUpx4",
  },
  {
    id: 7,
    name: "Dragon Ball Z",
    query: "Vegeta's sacrifice - Dragon Ball Z OST",
    year: 1989,
    genre: "Action",
    youtubeId: "VPMPCEHwFS8",
  },
  {
    id: 8,
    name: "Fullmetal Alchemist Brotherhood",
    query: "Trisha's Lullaby",
    year: 2003,
    genre: "Action",
    youtubeId: "hBkh7DRNqw8",
  },
  {
    id: 9,
    name: "Hunter x Hunter",
    query: "Ansatsu Ikka no Yakata",
    year: 2011,
    genre: "Adventure",
    youtubeId: "gdNcfEGcwr0",
  },
  {
    id: 10,
    name: "Jujutsu Kaisen",
    query: "Jujutsu Kaisen OST - Yuuji's Rage (One’s Innermost Thoughts)",
    year: 2020,
    genre: "Action",
    youtubeId: "y3PB03SvEcs",
  },

  // === SEINEN ===
  {
    id: 11,
    name: "Death Note",
    query: "Death Note - (N's Theme A) Music",
    year: 2006,
    genre: "Thriller",
    youtubeId: "WJW_ldC7sUA",
  },
  {
    id: 12,
    name: "Tokyo Ghoul",
    query: "Tokyo Ghoul - Aogiri theme",
    year: 2014,
    genre: "Horror",
    youtubeId: "B4ibOrDx_gg",
  },
  {
    id: 13,
    name: "Parasyte",
    query: "[OST] Parasyte - I AM",
    year: 2014,
    genre: "Horror",
    youtubeId: "vxLbI80RdYs",
  },
  {
    id: 14,
    name: "Steins;Gate",
    query: "steins gate opening hacking to the gate",
    year: 2011,
    genre: "Sci-Fi",
    youtubeId: "dy7gr0vaNho",
  },
  {
    id: 15,
    name: "Psycho-Pass",
    query: "Psycho-Pass OST : PSYCHO-PASS",
    year: 2012,
    genre: "Sci-Fi",
    youtubeId: "PRGV4FEQFf4",
  },
  {
    id: 16,
    name: "Monster",
    query: "monster opening grain",
    year: 2004,
    genre: "Thriller",
    youtubeId: "s6xRWH10KI0",
  },
  {
    id: 18,
    name: "Vinland Saga",
    query: "vinland saga opening mukanjyo",
    year: 2019,
    genre: "Action",
    youtubeId: "l5wAdQ-UkWY",
  },
  {
    id: 19,
    name: "Mob Psycho 100",
    query: "mob psycho 100 opening 99",
    year: 2016,
    genre: "Action",
    youtubeId: "Bw-5Lka7gPE",
  },
  {
    id: 20,
    name: "One Punch Man",
    query: "「Creditless」One Punch Man OP / Opening 2「UHD 60FPS」",
    year: 2015,
    genre: "Action",
    youtubeId: "OvgBFgLUyC8",
  },

  // === ROMANCE / SLICE OF LIFE ===
  {
    id: 21,
    name: "Your Lie in April",
    query: "your lie in april opening hikaru nara",
    year: 2014,
    genre: "Romance",
    youtubeId: "fWRPihlt2ho",
  },
  {
    id: 22,
    name: "Toradora",
    query: "toradora opening pre parade",
    year: 2008,
    genre: "Romance",
    youtubeId: "ylPEBnmRRxQ",
  },
  {
    id: 23,
    name: "Clannad",
    query: "clannad opening megumeru",
    year: 2007,
    genre: "Drama",
    youtubeId: "zgB0Y_BUvFE",
  },
  {
    id: 26,
    name: "Fruits Basket",
    query: "fruits basket opening again",
    year: 2019,
    genre: "Romance",
    youtubeId: "CzhI2NjuLyM",
  },
  {
    id: 27,
    name: "Kaguya-sama",
    query: "kaguya sama love is war opening love dramatic",
    year: 2019,
    genre: "Comedy",
    youtubeId: "WZof19wk4Ec",
  },
  {
    id: 28,
    name: "Horimiya",
    query: "horimiya opening iro kousui",
    year: 2021,
    genre: "Romance",
    youtubeId: "7DpONAPM3Zw",
  },
  {
    id: 29,
    name: "Oregairu",
    query: "oregairu opening yukitoki",
    year: 2013,
    genre: "Romance",
    youtubeId: "Q1W6oINBrnE",
  },
  {
    id: 30,
    name: "Violet Evergarden",
    query: "violet evergarden opening sincerely",
    year: 2018,
    genre: "Drama",
    youtubeId: "ZAKuyZEyZjY",
  },

  // === ISEKAI / FANTASY ===
  {
    id: 31,
    name: "Sword Art Online",
    query: "sword art online At Nightfall",
    year: 2012,
    genre: "Isekai",
    youtubeId: "zWDrH1jJ3gE",
  },
  {
    id: 32,
    name: "Re:Zero",
    query: "re zero opening redo",
    year: 2016,
    genre: "Isekai",
    youtubeId: "0Vwwr3VGsYg",
  },
  {
    id: 33,
    name: "Overlord",
    query: "overlord opening clattanoia",
    year: 2015,
    genre: "Isekai",
    youtubeId: "KOWcj7XKnfQ",
  },
  {
    id: 34,
    name: "Konosuba",
    query: "konosuba opening fantastic dreamer",
    year: 2016,
    genre: "Comedy",
    youtubeId: "fpG3BPNQepY",
  },
  {
    id: 35,
    name: "That Time I Got Reincarnated as a Slime",
    query: "slime opening nameless story",
    year: 2018,
    genre: "Isekai",
    youtubeId: "ZhvUomsfG8o",
  },
  {
    id: 36,
    name: "The Rising of the Shield Hero op saison 3",
    query: "The Rising of the Shield Hero Season 3 Opening ",
    year: 2019,
    genre: "Isekai",
    youtubeId: "-ZGrwqpwSQs",
  },
  {
    id: 37,
    name: "Mushoku Tensei",
    query: "mushoku tensei opening tabibito no uta",
    year: 2021,
    genre: "Isekai",
    youtubeId: "QG8UZUahRbI",
  },
  {
    id: 38,
    name: "No Game No Life",
    query: "Anime de Japan - All Of You Is All Of Me Theme (No Game No Life)",
    year: 2014,
    genre: "Isekai",
    youtubeId: "05Kx8us0xx0",
  },
  {
    id: 39,
    name: "Log Horizon",
    query: "log horizon opening database",
    year: 2013,
    genre: "Isekai",
    youtubeId: "eW6sEkTGbUc",
  },
  {
    id: 40,
    name: "Grimgar",
    query: "grimgar opening knew day",
    year: 2016,
    genre: "Isekai",
    youtubeId: "sO4DEqVzlD4",
  },

  // === SPORTS ===
  {
    id: 41,
    name: "Haikyuu",
    query: "Haikyuu!! OST - Omnivorous",
    year: 2014,
    genre: "Sports",
    youtubeId: "isy3ikkIpqw",
  },
  {
    id: 42,
    name: "Kuroko no Basket",
    query: "Kuroko no Basket Season 2 - OST 05 Imminence",
    year: 2012,
    genre: "Sports",
    youtubeId: "aeZKSOYh5KE",
  },
  {
    id: 43,
    name: "Slam Dunk",
    query: "slam dunk opening kimi ga suki da to sakebitai",
    year: 1993,
    genre: "Sports",
    youtubeId: "YhkQvv6BMEs",
  },
  {
    id: 45,
    name: "Yuri on Ice",
    query: "yuri on ice opening history maker",
    year: 2016,
    genre: "Sports",
    youtubeId: "5u3RGhznctE",
  },
  {
    id: 46,
    name: "Hajime no Ippo",
    query: "hajime no ippo opening inner light",
    year: 2000,
    genre: "Sports",
    youtubeId: "dmdOSIzsq3Q",
  },
  {
    id: 47,
    name: "Ace of Diamond",
    query: "ace of diamond opening go exceed",
    year: 2013,
    genre: "Sports",
    youtubeId: "ViBE_zYivNc",
  },
  {
    id: 48,
    name: "Run with the Wind",
    query: "run with the wind opening catch up latent",
    year: 2018,
    genre: "Sports",
    youtubeId: "PxQI5f2Stbg",
  },
  {
    id: 50,
    name: "Blue Lock",
    query: "BLUELOCK Original Soundtrack : Despair",
    year: 2022,
    genre: "Sports",
    youtubeId: "WY1LPooUeBI",
  },

  // === MECHA / SCI-FI ===
  {
    id: 51,
    name: "Neon Genesis Evangelion",
    query: "Kokoro Yo Genshi ni Modoru - Evangelion Alternate Opening 2",
    year: 1995,
    genre: "Mecha",
    youtubeId: "V1MdqanqJ5o",
  },
  {
    id: 53,
    name: "Gurren Lagann",
    query: "gurren lagann opening sorairo days",
    year: 2007,
    genre: "Mecha",
    youtubeId: "PKRUKalbx3s",
  },
  {
    id: 54,
    name: "Cowboy Bebop",
    query: "cowboy bebop opening tank",
    year: 1998,
    genre: "Sci-Fi",
    youtubeId: "0hfOyOBHIq4",
  },
  {
    id: 55,
    name: "Gundam",
    query: "gundam opening",
    year: 1979,
    genre: "Mecha",
    youtubeId: "oNJ4aBoRipg",
  },
  {
    id: 56,
    name: "Darling in the Franxx",
    query: "darling in the franxx opening kiss of death",
    year: 2018,
    genre: "Mecha",
    youtubeId: "A4kLcDWBYcQ",
  },
  {
    id: 58,
    name: "Aldnoah.Zero",
    query: "【ALDNOAH ZERO】-OPENING 2 HD アルドノアゼロ OP 2",
    year: 2014,
    genre: "Mecha",
    youtubeId: "txiYc9FEUzY",
  },
  {
    id: 59,
    name: "Knights of Sidonia",
    query: "knights of sidonia opening sidonia",
    year: 2014,
    genre: "Mecha",
    youtubeId: "G_zn1a-dOvg",
  },
  {
    id: 60,
    name: "SSSS.Gridman",
    query: "gridman opening union",
    year: 2018,
    genre: "Mecha",
    youtubeId: "0PnikGsbjJM",
  },

  // === CLASSIQUES / NOSTALGIE ===
  {
    id: 61,
    name: "Sailor Moon",
    query: "sailor moon opening moonlight densetsu",
    year: 1992,
    genre: "Magical Girl",
    youtubeId: "R-DHOG6c2V8",
  },
  {
    id: 62,
    name: "Pokemon",
    query: "pokemon theme song",
    year: 1997,
    genre: "Adventure",
    youtubeId: "JuYeHPFR3f0",
  },
  {
    id: 63,
    name: "Yu-Gi-Oh",
    query: "yugioh opening 5 OVERLAP",
    year: 2000,
    genre: "Adventure",
    youtubeId: "o_Z0AhbSQxo",
  },
  {
    id: 64,
    name: "Digimon",
    query: "digimon opening butterfly",
    year: 1999,
    genre: "Adventure",
    youtubeId: "jB7ecG_12x8",
  },
  {
    id: 65,
    name: "Inuyasha",
    query: "inuyasha opening change the world",
    year: 2000,
    genre: "Fantasy",
    youtubeId: "BbHsd4PAME0",
  },
  {
    id: 66,
    name: "Cardcaptor Sakura",
    query: "cardcaptor sakura opening catch you catch me",
    year: 1998,
    genre: "Magical Girl",
    youtubeId: "6gpcPYDkPdg",
  },
  {
    id: 67,
    name: "Rurouni Kenshin",
    query: "rurouni kenshin opening sobakasu",
    year: 1996,
    genre: "Action",
    youtubeId: "0DBkXcDU270",
  },
  {
    id: 68,
    name: "Trigun",
    query: "trigun opening h t",
    year: 1998,
    genre: "Action",
    youtubeId: "4OxFSy8G5wk",
  },
  {
    id: 69,
    name: "Outlaw Star",
    query: "outlaw star opening through the night",
    year: 1998,
    genre: "Sci-Fi",
    youtubeId: "dAMCYV8iQNg",
  },
  {
    id: 70,
    name: "Ghost in the Shell",
    query: "ghost in the shell opening inner universe",
    year: 2002,
    genre: "Sci-Fi",
    youtubeId: "dP4t_GGl3Es",
  },

  // === RÉCENTS / POPULAIRES ===
  {
    id: 71,
    name: "Chainsaw Man",
    query: "chainsaw man opening kick back",
    year: 2022,
    genre: "Action",
    youtubeId: "dFlDRhvM4L0",
  },
  {
    id: 72,
    name: "Spy x Family",
    query: "spy family opening mixed nuts",
    year: 2022,
    genre: "Comedy",
    youtubeId: "U_rWZK_8vUY",
  },
  {
    id: 73,
    name: "Cyberpunk Edgerunners",
    query: "cyberpunk edgerunners opening this fffire",
    year: 2022,
    genre: "Sci-Fi",
    youtubeId: "mH2wmyeiIpA",
  },
  {
    id: 74,
    name: "Bocchi the Rock",
    query: "bocchi the rock opening seishun complex",
    year: 2022,
    genre: "Music",
    youtubeId: "dlSbEP4V-gI",
  },
  {
    id: 75,
    name: "Lycoris Recoil",
    query: "lycoris recoil opening alive",
    year: 2022,
    genre: "Action",
    youtubeId: "6pWwVrVUsGo",
  },
  {
    id: 76,
    name: "Oshi No Ko - Ending 1",
    query: "Oshi No Ko - Ending 1 (Mephisto) | 4K UHD Creditless | Subtitles",
    year: 2023,
    genre: "Drama",
    youtubeId: "ZRtdQ81jPUQ",
  },
  {
    id: 77,
    name: "Frieren",
    query: "Dragon Smasher",
    year: 2023,
    genre: "Fantasy",
    youtubeId: "lrBUdDDHflU",
  },
  {
    id: 78,
    name: "Mashle",
    query: "mashle opening bling bang bang born",
    year: 2023,
    genre: "Comedy",
    youtubeId: "210R0ozmLwg",
  },
  {
    id: 79,
    name: "Hell's Paradise",
    query: "hells paradise opening work",
    year: 2023,
    genre: "Action",
    youtubeId: "04WuoQMhhxw",
  },
  {
    id: 80,
    name: "The Dangers in My Heart",
    query: "dangers in my heart opening chime",
    year: 2023,
    genre: "Romance",
    youtubeId: "i3r4geiaMLs",
  },

  // === HORREUR / THRILLER ===
  {
    id: 82,
    name: "Elfen Lied",
    query: "elfen lied opening lilium",
    year: 2004,
    genre: "Horror",
    youtubeId: "f3KzmVblyHw",
  },
  {
    id: 83,
    name: "Higurashi",
    query: "higurashi opening higurashi no naku koro ni",
    year: 2006,
    genre: "Horror",
    youtubeId: "XgWkIrFQQE0",
  },
  {
    id: 84,
    name: "The Promised Neverland",
    query: "Isabella's Lullaby (vocal and mandolin ver.)",
    year: 2019,
    genre: "Thriller",
    youtubeId: "a2DWZeYfoCQ",
  },
  {
    id: 85,
    name: "Mirai Nikki",
    query: "mirai nikki opening kuusou mesorogiwi",
    year: 2011,
    genre: "Thriller",
    youtubeId: "ZZvJY7_gyfw",
  },
  {
    id: 86,
    name: "Terror in Resonance",
    query: "terror in resonance opening trigger",
    year: 2014,
    genre: "Thriller",
    youtubeId: "g1ARRcK4LVs",
  },
  {
    id: 87,
    name: "Corpse Party",
    query: "corpse party opening shangri-la",
    year: 2013,
    genre: "Horror",
    youtubeId: "wiZ_4Qr9jL4",
  },
  {
    id: 88,
    name: "Shiki",
    query: "shiki opening kuchizuke",
    year: 2010,
    genre: "Horror",
    youtubeId: "Dqtm2DrcKWg",
  },
  {
    id: 89,
    name: "Hell Girl",
    query: "hell girl opening sakasama no chou",
    year: 2005,
    genre: "Horror",
    youtubeId: "Ft1D1coUmOM",
  },
  {
    id: 90,
    name: "Deadman Wonderland",
    query: "deadman wonderland opening one reason",
    year: 2011,
    genre: "Action",
    youtubeId: "2pZ-UpjtlXY",
  },

  // === DIVERS ===
  {
    id: 92,
    name: "Dr. Stone",
    query: "'A Dogfight Theme'『ドクターストーン』Dr. Stone S4 EP10 OST Cover",
    year: 2019,
    genre: "Sci-Fi",
    youtubeId: "3s6odgnJv6c",
  },
  {
    id: 93,
    name: "The Disastrous Life of Saiki K",
    query: "saiki k opening seishun wa zankoku janai",
    year: 2016,
    genre: "Comedy",
    youtubeId: "4GNTfA-seHY",
  },
  {
    id: 94,
    name: "Assassination Classroom",
    query: "assassination classroom opening seishun satsubatsuron",
    year: 2015,
    genre: "Action",
    youtubeId: "A41jCFkGiX0",
  },
  {
    id: 95,
    name: "Black Clover",
    query: "black clover opening haruka mirai",
    year: 2017,
    genre: "Action",
    youtubeId: "_6KZI74zKfE",
  },
  {
    id: 96,
    name: "Fire Force",
    query: "fire force opening inferno",
    year: 2019,
    genre: "Action",
    youtubeId: "JBqxVX_LXvk",
  },
  {
    id: 97,
    name: "Dorohedoro",
    query: "dorohedoro opening welcome to chaos",
    year: 2020,
    genre: "Dark Fantasy",
    youtubeId: "BK0tDxrzUOc",
  },
  {
    id: 98,
    name: "Made in Abyss",
    query:
      "Made in Abyss OST - Pathway (Goodbye My Friend) [メイドインアビス OST]",
    year: 2017,
    genre: "Adventure",
    youtubeId: "nk8COybCLuU",
  },
  {
    id: 99,
    name: "The Ancient Magus Bride",
    query: "ancient magus bride opening here",
    year: 2017,
    genre: "Fantasy",
    youtubeId: "KuZbmLLv1vM",
  },
  {
    id: 100,
    name: "Noragami",
    query: "noragami opening goya no machiawase",
    year: 2014,
    genre: "Action",
    youtubeId: "gWCnKoEgfP0",
  },
  {
    id: 101,
    name: "Mobile Suit Gundam 00",
    query: "gundam 00 Fight ost",
    year: 2007,
    genre: "Mecha",
    youtubeId: "gM_xBLjtIH0",
  },
  {
    id: 103,
    name: "Hellsing Ultimate",
    query: "gradus vita",
    year: 2006,
    genre: "Action",
    youtubeId: "1d9hMAxKJ5Q",
  },
  {
    id: 104,
    name: "Serial Experiments Lain",
    query: "serial experiments lain opening duvet",
    year: 1998,
    genre: "Sci-Fi",
    youtubeId: "Uoox9fpmDP0",
  },
  {
    id: 105,
    name: "Akira",
    query: "akira ost kaneda",
    year: 1988,
    genre: "Sci-Fi",
    youtubeId: "Nja0Obgg2gU",
  },
  {
    id: 106,
    name: "Patlabor",
    query: "patlabor opening",
    year: 1989,
    genre: "Mecha",
    youtubeId: "Z9UtUzjUA5Q",
  },
  {
    id: 108,
    name: "Gunbuster",
    query: "gunbuster opening active heart",
    year: 1988,
    genre: "Mecha",
    youtubeId: "ZLhPBQpXafY",
  },
  {
    id: 109,
    name: "Macross",
    query: "macross opening",
    year: 1982,
    genre: "Mecha",
    youtubeId: "I4aQQBLokNo",
  },

  // === SEINEN / ACTION ===
  {
    id: 111,
    name: "Terra Formars",
    query: "terraformars opening",
    year: 2014,
    genre: "Action",
    youtubeId: "QW7HU71YRkg",
  },
  {
    id: 112,
    name: "Kengan Ashura",
    query: "kengan ashura opening king and ashura",
    year: 2019,
    genre: "Action",
    youtubeId: "OxNeZiOr_zs",
  },
  {
    id: 113,
    name: "Kakegurui",
    query: "kakegurui opening deal with the devil",
    year: 2017,
    genre: "Thriller",
    youtubeId: "pJ-MywdW98o",
  },
  {
    id: 114,
    name: "Golgo 13",
    query: "golgo 13 opening",
    year: 1983,
    genre: "Action",
    youtubeId: "pu8COKiheGo",
  },
  {
    id: 115,
    name: "City Hunter",
    query: "city hunter opening get wild",
    year: 1987,
    genre: "Action",
    youtubeId: "zhLdgee_EXk",
  },
  {
    id: 116,
    name: "Space Cobra",
    query: "space cobra opening",
    year: 1982,
    genre: "Sci-Fi",
    youtubeId: "dt6XXfcdVY0",
  },
  {
    id: 117,
    name: "City Hunter",
    query: "city hunter footsteps",
    year: 1987,
    genre: "Action",
    youtubeId: "EOW9f_Pdmjk",
  },
  {
    id: 118,
    name: "Dragon Ball Super",
    query:
      "Dragon Ball Super OST - Vegeta’s New Form (Original SoundTrack) Quality HD",
    year: 2018,
    genre: "Action",
    youtubeId: "du_SYMFfbG4",
  },
  {
    id: 119,
    name: "Captain Tsubasa",
    query: 'Captain Tsubasa 1983 Original Soundtrack Misugi Jun"',
    year: 1983,
    genre: "Sports",
    youtubeId: "eAXYyC3TrdM",
  },
  {
    id: 120,
    name: "Hokuto no Ken",
    query:
      "Fist of the North Star - Opening 1 v1 【Ai wo Torimodose!!】 4K / UHD Creditless | CC",
    year: 1984,
    genre: "Action",
    youtubeId: "pRFxpHSNxkA",
  },
  {
    id: 121,
    name: "Saint Seiya",
    query: "Saint Seiya Opening 2 - Soldier Dream (Asgard Arc)",
    year: 1986,
    genre: "Action",
    youtubeId: "JUJP5eAxcIA",
  },
  {
    id: 122,
    name: "Cats Eye",
    query: "Cat's Eye Anime Intro Opening Theme HD",
    year: 1986,
    genre: "Action",
    youtubeId: "qcqQIt-dF-E",
  },
];
