// data/movies.ts
export const movies = [
  // === ACTION / AVENTURE ===
  {
    id: 1,
    name: "Star Wars",
    query: "star wars main theme john williams",
    year: 1977,
    genre: "Sci-Fi",
    youtubeId: "54hoKbTWon4",
  },
  {
    id: 2,
    name: "Indiana Jones",
    query: "indiana jones theme raiders march",
    year: 1981,
    genre: "Adventure",
    youtubeId: "VVYFvL5S7nU",
  },
  {
    id: 3,
    name: "James Bond",
    query: "james bond theme",
    year: 1962,
    genre: "Action",
    youtubeId: "vyQ90OZLLtA",
  },
  {
    id: 4,
    name: "Mission Impossible",
    query: "mission impossible theme",
    year: 1996,
    genre: "Action",
    youtubeId: "XAYhNHhxN0A",
  },
  {
    id: 5,
    name: "The Avengers",
    query: "avengers theme alan silvestri",
    year: 2012,
    genre: "Action",
    youtubeId: "FxxhJXBjbIw",
  },
  {
    id: 6,
    name: "Iron Man",
    query: "iron man black sabbath",
    year: 2008,
    genre: "Action",
    youtubeId: "b3-QqGVt-tM",
  },
  {
    id: 7,
    name: "Guardians of the Galaxy",
    query: "guardians galaxy hooked on a feeling",
    year: 2014,
    genre: "Sci-Fi",
    youtubeId: "NrI-UBIB8Jk",
  },
  {
    id: 8,
    name: "Spider-Man",
    query: "spider man theme",
    year: 2002,
    genre: "Action",
    youtubeId: "5VL8bhqXppQ",
  },
  {
    id: 9,
    name: "Batman",
    query: "batman theme danny elfman",
    year: 1989,
    genre: "Action",
    youtubeId: "kRZAk2rfESU",
  },
  {
    id: 10,
    name: "Superman",
    query: "superman theme john williams",
    year: 1978,
    genre: "Action",
    youtubeId: "78N2SP6JFaI",
  },

  // === HORREUR ===
  {
    id: 11,
    name: "Halloween",
    query: "halloween theme john carpenter",
    year: 1978,
    genre: "Horror",
    youtubeId: "EAkmG-VH_O4",
  },
  {
    id: 12,
    name: "The Exorcist",
    query: "exorcist theme tubular bells",
    year: 1973,
    genre: "Horror",
    youtubeId: "FN6jIvKiYOs",
  },
  {
    id: 13,
    name: "Psycho",
    query: "psycho theme bernard herrmann",
    year: 1960,
    genre: "Horror",
    youtubeId: "_toChnTOwHE",
  },
  {
    id: 14,
    name: "Jaws",
    query: "jaws theme john williams",
    year: 1975,
    genre: "Horror",
    youtubeId: "E-sX2Y0W8l0",
  },
  {
    id: 15,
    name: "A Nightmare on Elm Street",
    query: "nightmare elm street theme",
    year: 1984,
    genre: "Horror",
    youtubeId: "1UruKZqvEHY",
  },
  {
    id: 16,
    name: "Friday the 13th",
    query: "friday 13th theme",
    year: 1980,
    genre: "Horror",
    youtubeId: "E6P4iatMl7M",
  },
  {
    id: 17,
    name: "Scream",
    query: "scream theme",
    year: 1996,
    genre: "Horror",
    youtubeId: "PfomTz_-jPY",
  },
  {
    id: 18,
    name: "The Shining",
    query: "shining theme dies irae",
    year: 1980,
    genre: "Horror",
    youtubeId: "uiisMznOdYo",
  },
  {
    id: 19,
    name: "The Thing",
    query: "the thing theme ennio morricone",
    year: 1982,
    genre: "Horror",
    youtubeId: "SsMH-sdznh8",
  },
  {
    id: 20,
    name: "It",
    query: "it theme benjamin wallfisch",
    year: 2017,
    genre: "Horror",
    youtubeId: "81fnZpIm7MA",
  },

  // === CLASSIQUES ===
  {
    id: 21,
    name: "The Godfather",
    query: "godfather theme nino rota",
    year: 1972,
    genre: "Crime",
    youtubeId: "X-jdl9hcCeg",
  },
  {
    id: 22,
    name: "Rocky",
    query: "rocky theme gonna fly now",
    year: 1976,
    genre: "Sports",
    youtubeId: "Qwu5zWTEYVs",
  },
  {
    id: 23,
    name: "Titanic",
    query: "titanic my heart will go on",
    year: 1997,
    genre: "Romance",
    youtubeId: "F2RnxZnubCM",
  },
  {
    id: 24,
    name: "Forrest Gump",
    query: "forrest gump theme alan silvestri",
    year: 1994,
    genre: "Drama",
    youtubeId: "ps_RXJ69iQA",
  },
  {
    id: 26,
    name: "Jurassic Park",
    query: "jurassic park theme john williams",
    year: 1993,
    genre: "Adventure",
    youtubeId: "-NqaupGcCpw",
  },
  {
    id: 27,
    name: "E.T.",
    query: "et theme john williams",
    year: 1982,
    genre: "Sci-Fi",
    youtubeId: "Ps1-YlB1TIQ",
  },
  {
    id: 28,
    name: "Back to the Future",
    query: "back to future theme alan silvestri",
    year: 1985,
    genre: "Sci-Fi",
    youtubeId: "8083S4dXP3k",
  },
  {
    id: 29,
    name: "Ghostbusters",
    query: "ghostbusters theme ray parker jr",
    year: 1984,
    genre: "Comedy",
    youtubeId: "TaV1r341wYk",
  },
  {
    id: 30,
    name: "Top Gun",
    query: "top gun danger zone kenny loggins",
    year: 1986,
    genre: "Action",
    youtubeId: "siwpn14IE7E",
  },

  // === SCI-FI ===
  {
    id: 41,
    name: "Blade Runner",
    query: "blade runner theme vangelis",
    year: 1982,
    genre: "Sci-Fi",
    youtubeId: "A03x9uw25kI",
  },
  {
    id: 42,
    name: "The Matrix",
    query: "matrix theme",
    year: 1999,
    genre: "Sci-Fi",
    youtubeId: "pFS4zYWxzNA",
  },
  {
    id: 43,
    name: "Interstellar",
    query: "interstellar theme hans zimmer",
    year: 2014,
    genre: "Sci-Fi",
    youtubeId: "UDVtMYqUAyw",
  },
  {
    id: 44,
    name: "Inception",
    query: "inception time hans zimmer",
    year: 2010,
    genre: "Sci-Fi",
    youtubeId: "j1M9tZGznx0",
  },
  {
    id: 45,
    name: "Dune",
    query: "dune theme hans zimmer",
    year: 2021,
    genre: "Sci-Fi",
    youtubeId: "uTmBeR32GRA",
  },
  {
    id: 46,
    name: "Tron Legacy",
    query: "tron legacy theme daft punk",
    year: 2010,
    genre: "Sci-Fi",
    youtubeId: "UOYk5qT3ffo",
  },
  {
    id: 47,
    name: "The Terminator",
    query: "terminator theme brad fiedel",
    year: 1984,
    genre: "Sci-Fi",
    youtubeId: "o24HFL1TRGE",
  },
  {
    id: 48,
    name: "Alien",
    query: "alien theme jerry goldsmith",
    year: 1979,
    genre: "Sci-Fi",
    youtubeId: "yc94TrMnwaw",
  },
  {
    id: 49,
    name: "2001 Space Odyssey",
    query: "2001 space odyssey also sprach zarathustra",
    year: 1968,
    genre: "Sci-Fi",
    youtubeId: "BekjyAH7c2A",
  },
  {
    id: 50,
    name: "Arrival",
    query: "arrival theme johann johannsson",
    year: 2016,
    genre: "Sci-Fi",
    youtubeId: "mdZjJacozBc",
  },

  // === FANTAISIE ===
  {
    id: 51,
    name: "Harry Potter",
    query: "harry potter hedwig theme john williams",
    year: 2001,
    genre: "Fantasy",
    youtubeId: "wtHra9tFISY",
  },
  {
    id: 52,
    name: "Lord of the Rings",
    query: "lord of the rings concerning hobbits",
    year: 2001,
    genre: "Fantasy",
    youtubeId: "9o_uCepqwso",
  },
  {
    id: 53,
    name: "The Hobbit",
    query: "hobbit theme howard shore",
    year: 2012,
    genre: "Fantasy",
    youtubeId: "CL_3mlOPnGI",
  },
  {
    id: 54,
    name: "Pirates of the Caribbean",
    query: "pirates caribbean he's a pirate",
    year: 2003,
    genre: "Adventure",
    youtubeId: "yRh-dzrI4Z4",
  },
  {
    id: 55,
    name: "The Chronicles of Narnia",
    query: "narnia theme harry gregson williams",
    year: 2005,
    genre: "Fantasy",
    youtubeId: "uzs6TYelnxU",
  },
  {
    id: 56,
    name: "Pan's Labyrinth",
    query: "pans labyrinth lullaby",
    year: 2006,
    genre: "Fantasy",
    youtubeId: "19bBGxf5k6k",
  },
  {
    id: 57,
    name: "Stardust",
    query: "stardust theme ilan eshkeri",
    year: 2007,
    genre: "Fantasy",
    youtubeId: "0JvzVB7TWEM",
  },
  {
    id: 58,
    name: "Willow",
    query: "willow theme james horner",
    year: 1988,
    genre: "Fantasy",
    youtubeId: "PKiXsJ0rQhU",
  },
  {
    id: 59,
    name: "The NeverEnding Story",
    query: "neverending story theme limahl",
    year: 1984,
    genre: "Fantasy",
    youtubeId: "lHytjEj7B9g",
  },
  {
    id: 60,
    name: "Labyrinth",
    query: "labyrinth magic dance david bowie",
    year: 1986,
    genre: "Fantasy",
    youtubeId: "j6NqnYYmSVE",
  },

  // === THRILLER / CRIME ===
  {
    id: 61,
    name: "Pulp Fiction",
    query: "pulp fiction misirlou dick dale",
    year: 1994,
    genre: "Crime",
    youtubeId: "2T8As2kzelk",
  },
  {
    id: 62,
    name: "The Dark Knight",
    query: "dark knight theme hans zimmer",
    year: 2008,
    genre: "Action",
    youtubeId: "CpAkBWG8eu8",
  },
  {
    id: 63,
    name: "Fight Club",
    query: "fight club where is my mind pixies",
    year: 1999,
    genre: "Thriller",
    youtubeId: "Y001O8Azj1U",
  },
  {
    id: 64,
    name: "Se7en",
    query: "se7en closer nine inch nails",
    year: 1995,
    genre: "Thriller",
    youtubeId: "mQFn5VbHLOw",
  },
  {
    id: 65,
    name: "The Silence of the Lambs",
    query: "silence of the lambs theme howard shore",
    year: 1991,
    genre: "Thriller",
    youtubeId: "ciP_WVFXs9g",
  },
  {
    id: 66,
    name: "Goodfellas",
    query: "goodfellas layla derek and the dominos",
    year: 1990,
    genre: "Crime",
    youtubeId: "DpkIlO2lgAE",
  },
  {
    id: 67,
    name: "Casino",
    query: "casino theme",
    year: 1995,
    genre: "Crime",
    youtubeId: "nLT68bx1_EM",
  },
  {
    id: 68,
    name: "Heat",
    query: "heat theme elliot goldenthal",
    year: 1995,
    genre: "Crime",
    youtubeId: "etB56TutHVs",
  },
  {
    id: 69,
    name: "No Country for Old Men",
    query: "no country old men theme",
    year: 2007,
    genre: "Thriller",
    youtubeId: "vwGnW5L_Zrw",
  },
  {
    id: 70,
    name: "Gone Girl",
    query: "gone girl theme trent reznor",
    year: 2014,
    genre: "Thriller",
    youtubeId: "EBaa0k1y57w",
  },

  // === COMÉDIE ===
  {
    id: 71,
    name: "The Pink Panther",
    query: "pink panther theme henry mancini",
    year: 1963,
    genre: "Comedy",
    youtubeId: "3jxgL_wZiFo",
  },
  {
    id: 72,
    name: "Austin Powers",
    query: "austin powers soul bossa nova",
    year: 1997,
    genre: "Comedy",
    youtubeId: "SaCiaQR8x4c",
  },
  {
    id: 73,
    name: "Ferris Bueller's Day Off",
    query: "ferris bueller oh yeah yello",
    year: 1986,
    genre: "Comedy",
    youtubeId: "2cPmiQwXc4U",
  },
  {
    id: 74,
    name: "The Blues Brothers",
    query: "blues brothers everybody needs somebody",
    year: 1980,
    genre: "Comedy",
    youtubeId: "wDvIGZ-_au4",
  },
  {
    id: 75,
    name: "Monty Python",
    query: "monty python always look on bright side",
    year: 1979,
    genre: "Comedy",
    youtubeId: "GvIjNpFZQtE",
  },
  {
    id: 76,
    name: "Shrek",
    query: "shrek all star smash mouth",
    year: 2001,
    genre: "Animation",
    youtubeId: "SWFA0d2vIUk",
  },
  {
    id: 77,
    name: "School of Rock",
    query: "school of rock theme",
    year: 2003,
    genre: "Comedy",
    youtubeId: "felGSDNwI1g",
  },
  {
    id: 78,
    name: "Napoleon Dynamite",
    query: "napoleon dynamite canned heat jamiroquai",
    year: 2004,
    genre: "Comedy",
    youtubeId: "Fr1r1KINlvU",
  },
  {
    id: 79,
    name: "Superbad",
    query: "superbad theme",
    year: 2007,
    genre: "Comedy",
    youtubeId: "-jEpt1Ytm-g",
  },
  {
    id: 80,
    name: "The Hangover",
    query: "hangover three best friends zach galifianakis",
    year: 2009,
    genre: "Comedy",
    youtubeId: "xsGP35Vd6qQ",
  },

  // === DRAME ===
  {
    id: 81,
    name: "Schindler's List",
    query: "schindlers list theme john williams",
    year: 1993,
    genre: "Drama",
    youtubeId: "057A1RdssoU",
  },
  {
    id: 82,
    name: "Gladiator",
    query: "gladiator now we are free",
    year: 2000,
    genre: "Drama",
    youtubeId: "mQQKZ5cgybU",
  },
  {
    id: 83,
    name: "Braveheart",
    query: "braveheart theme james horner",
    year: 1995,
    genre: "Drama",
    youtubeId: "fZbPis_42m8",
  },
  {
    id: 84,
    name: "The Shawshank Redemption",
    query: "shawshank redemption theme thomas newman",
    year: 1994,
    genre: "Drama",
    youtubeId: "arsOwUMw7x4",
  },
  {
    id: 85,
    name: "A Beautiful Mind",
    query: "beautiful mind theme james horner",
    year: 2001,
    genre: "Drama",
    youtubeId: "eamiiuUmVz8",
  },
  {
    id: 86,
    name: "The Green Mile",
    query: "green mile theme thomas newman",
    year: 1999,
    genre: "Drama",
    youtubeId: "WdcOqc4RMnY",
  },
  {
    id: 87,
    name: "Good Will Hunting",
    query: "good will hunting theme danny elfman",
    year: 1997,
    genre: "Drama",
    youtubeId: "LaWUmO4B3Vk",
  },
  {
    id: 88,
    name: "Dead Poets Society",
    query: "dead poets society theme maurice jarre",
    year: 1989,
    genre: "Drama",
    youtubeId: "fYvffYsiRh8",
  },
  {
    id: 89,
    name: "Rain Man",
    query: "rain man theme hans zimmer",
    year: 1988,
    genre: "Drama",
    youtubeId: "fKZkIt0QRoM",
  },
  {
    id: 90,
    name: "The Pianist",
    query: "pianist theme wojciech kilar",
    year: 2002,
    genre: "Drama",
    youtubeId: "Aiqv2G41FcU",
  },

  // === RÉCENTS ===
  {
    id: 91,
    name: "Oppenheimer",
    query: "oppenheimer theme ludwig goransson",
    year: 2023,
    genre: "Drama",
    youtubeId: "4JZ-o3iAJv4",
  },
  {
    id: 93,
    name: "Everything Everywhere All at Once",
    query: "everything everywhere theme son lux",
    year: 2022,
    genre: "Sci-Fi",
    youtubeId: "Dh221GwdM-k",
  },
  {
    id: 94,
    name: "Dune Part Two",
    query: "dune 2 theme hans zimmer",
    year: 2024,
    genre: "Sci-Fi",
    youtubeId: "l4OOW_RShbE",
  },
  {
    id: 95,
    name: "The Batman",
    query: "the batman theme michael giacchino",
    year: 2022,
    genre: "Action",
    youtubeId: "Cwcinb2OxUo",
  },
  {
    id: 96,
    name: "Top Gun Maverick",
    query: "top gun maverick theme",
    year: 2022,
    genre: "Action",
    youtubeId: "cLZrAi0zrNI",
  },
  {
    id: 97,
    name: "Black Panther",
    query: "black panther theme ludwig goransson",
    year: 2018,
    genre: "Action",
    youtubeId: "WMFAsidiQfc",
  },
  {
    id: 98,
    name: "Joker",
    query: "joker theme hildur gudnadottir",
    year: 2019,
    genre: "Drama",
    youtubeId: "gSwbYHJYskM",
  },
  {
    id: 99,
    name: "1917",
    query: "1917 theme thomas newman",
    year: 2019,
    genre: "War",
    youtubeId: "gqo46lt-8Q4",
  },
  {
    id: 100,
    name: "No Time to Die",
    query: "no time to die billie eilish",
    year: 2021,
    genre: "Action",
    youtubeId: "BboMpayJomw",
  },
];
