// data/tv-shows.ts
export const tvShows = [
  // === DRAMES / CRIME ===
  {
    id: 1,
    name: "Breaking Bad",
    query: "breaking bad theme",
    year: 2008,
    genre: "Crime",
    youtubeId: "ilfYnhXD-bE",
  },
  {
    id: 2,
    name: "Game of Thrones",
    query: "game of thrones theme",
    year: 2011,
    genre: "Fantasy",
    youtubeId: "TZE9gVF1QbA",
  },
  {
    id: 3,
    name: "The Sopranos",
    query: "sopranos theme woke up this morning",
    year: 1999,
    genre: "Crime",
    youtubeId: "nW3LikcBL68",
  },
  {
    id: 4,
    name: "The Wire",
    query: "the wire theme way down in the hole",
    year: 2002,
    genre: "Crime",
    youtubeId: "5dxnr9fV-Ts",
  },
  {
    id: 5,
    name: "Better Call Saul",
    query: "better call saul theme",
    year: 2015,
    genre: "Crime",
    youtubeId: "yBm4K00SMEk",
  },
  {
    id: 6,
    name: "Dexter",
    query: "dexter theme",
    year: 2006,
    genre: "Crime",
    youtubeId: "4yMX84KyfKM",
  },
  {
    id: 7,
    name: "True Detective",
    query: "true detective theme far from any road",
    year: 2014,
    genre: "Crime",
    youtubeId: "Y4SjTUPC6gI",
  },
  {
    id: 8,
    name: "Narcos",
    query: "narcos theme tuyo rodrigo amarante",
    year: 2015,
    genre: "Crime",
    youtubeId: "zNPXnAVyAUA",
  },
  {
    id: 9,
    name: "Ozark",
    query: "ozark theme",
    year: 2017,
    genre: "Crime",
    youtubeId: "DJQxWhRIQE0",
  },
  {
    id: 10,
    name: "Peaky Blinders",
    query: "peaky blinders theme red right hand",
    year: 2013,
    genre: "Crime",
    youtubeId: "KGD2N5hJ2e0",
  },

  // === SCI-FI / FANTASY ===
  {
    id: 11,
    name: "Stranger Things",
    query: "stranger things theme",
    year: 2016,
    genre: "Sci-Fi",
    youtubeId: "-RcPZdihrp4",
  },
  {
    id: 12,
    name: "The Mandalorian",
    query: "mandalorian theme",
    year: 2019,
    genre: "Sci-Fi",
    youtubeId: "9qoDjHTc_Q8",
  },
  {
    id: 13,
    name: "Westworld",
    query: "westworld theme",
    year: 2016,
    genre: "Sci-Fi",
    youtubeId: "rYelEUVQ50g",
  },
  {
    id: 14,
    name: "The Witcher",
    query: "witcher toss a coin",
    year: 2019,
    genre: "Fantasy",
    youtubeId: "U9OQAySv184",
  },
  {
    id: 15,
    name: "Black Mirror",
    query: "black mirror theme",
    year: 2011,
    genre: "Sci-Fi",
    youtubeId: "G_K9xsSdgMs",
  },
  {
    id: 16,
    name: "Doctor Who",
    query: "doctor who theme",
    year: 2005,
    genre: "Sci-Fi",
    youtubeId: "c6E4IsTvPbI",
  },
  {
    id: 19,
    name: "Lost",
    query: "lost theme",
    year: 2004,
    genre: "Sci-Fi",
    youtubeId: "9LDh8DefWpI",
  },
  {
    id: 20,
    name: "Battlestar Galactica",
    query: "battlestar galactica theme",
    year: 2004,
    genre: "Sci-Fi",
    youtubeId: "vzyHxYxc-Mo",
  },

  // === COMÉDIES ===
  {
    id: 21,
    name: "The Office",
    query: "the office theme",
    year: 2005,
    genre: "Comedy",
    youtubeId: "0T-if-Vj2Xs",
  },
  {
    id: 22,
    name: "Friends",
    query: "friends theme i'll be there for you",
    year: 1994,
    genre: "Comedy",
    youtubeId: "S8PNXgLhkT0",
  },
  {
    id: 23,
    name: "How I Met Your Mother",
    query: "how i met your mother theme",
    year: 2005,
    genre: "Comedy",
    youtubeId: "elZBsxX6SEs",
  },
  {
    id: 24,
    name: "The Big Bang Theory",
    query: "big bang theory theme",
    year: 2007,
    genre: "Comedy",
    youtubeId: "CMSYv_Z4SI8",
  },
  {
    id: 25,
    name: "Parks and Recreation",
    query: "parks and recreation theme",
    year: 2009,
    genre: "Comedy",
    youtubeId: "wI7f4CgATiE",
  },
  {
    id: 26,
    name: "Brooklyn Nine-Nine",
    query: "brooklyn nine nine theme",
    year: 2013,
    genre: "Comedy",
    youtubeId: "ourfSzoC7pA",
  },
  {
    id: 27,
    name: "Seinfeld",
    query: "seinfeld theme",
    year: 1989,
    genre: "Comedy",
    youtubeId: "RWak0i_iqnM",
  },
  {
    id: 28,
    name: "Scrubs",
    query: "scrubs theme i'm no superman",
    year: 2001,
    genre: "Comedy",
    youtubeId: "U4zMv-yAxtQ",
  },
  {
    id: 29,
    name: "Arrested Development",
    query: "arrested development theme",
    year: 2003,
    genre: "Comedy",
    youtubeId: "4oIk04OQ1Ec",
  },

  // === DRAMES / PRESTIGE TV ===
  {
    id: 31,
    name: "House of Cards",
    query: "house of cards theme",
    year: 2013,
    genre: "Drama",
    youtubeId: "9w-O60x1bYk",
  },
  {
    id: 32,
    name: "Mad Men",
    query: "mad men theme",
    year: 2007,
    genre: "Drama",
    youtubeId: "vD12mZiFPtM",
  },
  {
    id: 33,
    name: "The Crown",
    query: "crown theme",
    year: 2016,
    genre: "Drama",
    youtubeId: "_46PNVriyOk",
  },
  {
    id: 34,
    name: "Succession",
    query: "succession theme",
    year: 2018,
    genre: "Drama",
    youtubeId: "LlgWqcHXD8w",
  },
  {
    id: 35,
    name: "Billions",
    query: "billions theme",
    year: 2016,
    genre: "Drama",
    youtubeId: "yJDht8hka5U",
  },
  {
    id: 36,
    name: "Homeland",
    query: "homeland theme",
    year: 2011,
    genre: "Drama",
    youtubeId: "5UgF4Y-S6fs",
  },
  {
    id: 37,
    name: "The Handmaid's Tale",
    query: "handmaids tale theme",
    year: 2017,
    genre: "Drama",
    youtubeId: "vVi7eKzXgRk",
  },
  {
    id: 38,
    name: "Big Little Lies",
    query: "big little lies theme cold little heart",
    year: 2017,
    genre: "Drama",
    youtubeId: "nOubjLM9Cbc",
  },

  // === HORREUR / THRILLER ===
  {
    id: 41,
    name: "The Walking Dead",
    query: "walking dead theme",
    year: 2010,
    genre: "Horror",
    youtubeId: "v5ISBJc1wFk",
  },
  {
    id: 42,
    name: "American Horror Story",
    query: "american horror story theme",
    year: 2011,
    genre: "Horror",
    youtubeId: "1qXiKIM0TKA",
  },
  {
    id: 43,
    name: "The Haunting of Hill House",
    query: "haunting of hill house theme",
    year: 2018,
    genre: "Horror",
    youtubeId: "dn2hzbeGcgI",
  },
  {
    id: 44,
    name: "Stranger Things",
    query: "stranger things theme",
    year: 2016,
    genre: "Horror",
    youtubeId: "-RcPZdihrp4",
  },
  {
    id: 45,
    name: "Chernobyl",
    query: "chernobyl theme",
    year: 2019,
    genre: "Drama",
    youtubeId: "4Poc3MF8GFk",
  },
  {
    id: 46,
    name: "Mindhunter",
    query: "mindhunter theme",
    year: 2017,
    genre: "Thriller",
    youtubeId: "4htQOlEwayM",
  },
  {
    id: 47,
    name: "True Blood",
    query: "true blood theme bad things",
    year: 2008,
    genre: "Horror",
    youtubeId: "sMPNjPpdjKU",
  },
  {
    id: 48,
    name: "Hannibal",
    query: "Bloodfest (From Mizumono) - Hannibal Soundtrack",
    year: 2013,
    genre: "Thriller",
    youtubeId: "Lqq6Ge0p6Yc",
  },
  {
    id: 50,
    name: "The Terror",
    query: "terror theme",
    year: 2018,
    genre: "Horror",
    youtubeId: "oPY5TmLBCOM",
  },

  // === ANIMÉES / JEUNESSE ===
  {
    id: 51,
    name: "Rick and Morty",
    query: "rick and morty theme",
    year: 2013,
    genre: "Animation",
    youtubeId: "wh10k2LPZiI",
  },
  {
    id: 52,
    name: "South Park",
    query: "south park theme",
    year: 1997,
    genre: "Animation",
    youtubeId: "Bdt0pz5C4Xc",
  },
  {
    id: 53,
    name: "Family Guy",
    query: "family guy theme",
    year: 1999,
    genre: "Animation",
    youtubeId: "eeNHV2C5m3w",
  },
  {
    id: 54,
    name: "The Simpsons",
    query: "simpsons theme",
    year: 1989,
    genre: "Animation",
    youtubeId: "Fttst9dG6Ko",
  },
  {
    id: 56,
    name: "Adventure Time",
    query: "adventure time theme",
    year: 2010,
    genre: "Animation",
    youtubeId: "cvDxko2Zm0Q",
  },
  {
    id: 57,
    name: "Gravity Falls",
    query: "gravity falls theme",
    year: 2012,
    genre: "Animation",
    youtubeId: "X2DUpDxFJyg",
  },
  {
    id: 59,
    name: "Futurama",
    query: "futurama theme",
    year: 1999,
    genre: "Animation",
    youtubeId: "QRk1s5Kf3aQ",
  },
  {
    id: 60,
    name: "SpongeBob SquarePants",
    query: "spongebob theme",
    year: 1999,
    genre: "Animation",
    youtubeId: "r9L4AseD-aA",
  },

  // === CLASSIQUES / RÉTRO ===
  {
    id: 61,
    name: "X-Files",
    query: "x files theme",
    year: 1993,
    genre: "Sci-Fi",
    youtubeId: "hAAlDoAtV7Y",
  },
  {
    id: 62,
    name: "Twin Peaks",
    query: "twin peaks theme",
    year: 1990,
    genre: "Mystery",
    youtubeId: "nCn3LYqCnrk",
  },
  {
    id: 63,
    name: "Buffy the Vampire Slayer",
    query: "buffy theme",
    year: 1997,
    genre: "Fantasy",
    youtubeId: "5-xnvdtuRRo",
  },
  {
    id: 64,
    name: "Gilmore Girls",
    query: "gilmore girls theme where you lead",
    year: 2000,
    genre: "Drama",
    youtubeId: "cSAtoSs7ZSI",
  },
  {
    id: 65,
    name: "Dawson's Creek",
    query: "dawsons creek theme i dont want to wait",
    year: 1998,
    genre: "Drama",
    youtubeId: "L_dVEtLPdDE",
  },
  {
    id: 66,
    name: "The Fresh Prince of Bel-Air",
    query: "fresh prince theme",
    year: 1990,
    genre: "Comedy",
    youtubeId: "1nCqRmx3Dnw",
  },
  {
    id: 67,
    name: "Cheers",
    query: "cheers theme where everybody knows your name",
    year: 1982,
    genre: "Comedy",
    youtubeId: "h-mi0r0LpXo",
  },
  {
    id: 68,
    name: "M*A*S*H",
    query: "mash theme suicide is painless",
    year: 1972,
    genre: "Comedy",
    youtubeId: "QOS6kfR9u4s",
  },
  {
    id: 69,
    name: "The Twilight Zone",
    query: "twilight zone theme",
    year: 1959,
    genre: "Sci-Fi",
    youtubeId: "XVSRm80WzZk",
  },
  {
    id: 70,
    name: "Miami Vice",
    query: "miami vice theme",
    year: 1984,
    genre: "Crime",
    youtubeId: "dEjXPY9jOx8",
  },

  // === RÉCENTES / POPULAIRES ===
  {
    id: 71,
    name: "Wednesday",
    query: "wednesday theme",
    year: 2022,
    genre: "Comedy",
    youtubeId: "vhBHaz9SaLI",
  },
  {
    id: 72,
    name: "The Last of Us",
    query: "last of us theme",
    year: 2023,
    genre: "Drama",
    youtubeId: "Pt1pOY3_W64",
  },
  {
    id: 73,
    name: "Squid Game",
    query: "squid game theme",
    year: 2021,
    genre: "Thriller",
    youtubeId: "YaZbrXAs5Wg",
  },
  {
    id: 74,
    name: "The Bear",
    query: "bear theme",
    year: 2022,
    genre: "Drama",
    youtubeId: "7f4J75lmkO0",
  },
  {
    id: 75,
    name: "Yellowstone",
    query: "yellowstone theme",
    year: 2018,
    genre: "Drama",
    youtubeId: "nIxPn7xWA_k",
  },
  {
    id: 76,
    name: "The Boys",
    query: "boys theme",
    year: 2019,
    genre: "Action",
    youtubeId: "2Q3dGZPguSM",
  },
  {
    id: 77,
    name: "Invincible",
    query: "invincible theme",
    year: 2021,
    genre: "Animation",
    youtubeId: "Fyom1YqBggI",
  },
  {
    id: 78,
    name: "Ted Lasso",
    query: "ted lasso theme",
    year: 2020,
    genre: "Comedy",
    youtubeId: "AIcis7S-byg",
  },
  {
    id: 79,
    name: "Severance",
    query: "severance theme",
    year: 2022,
    genre: "Thriller",
    youtubeId: "NmS3m0OG-Ug",
  },
  {
    id: 80,
    name: "Andor",
    query: "andor theme",
    year: 2022,
    genre: "Sci-Fi",
    youtubeId: "DbQAyWJxOQE",
  },

  // === ACTION / AVENTURE ===
  {
    id: 81,
    name: "Vikings",
    query: "vikings theme if i had a heart",
    year: 2013,
    genre: "Action",
    youtubeId: "USOsp5yQhZY",
  },
  {
    id: 82,
    name: "The Witcher",
    query: "witcher theme",
    year: 2019,
    genre: "Fantasy",
    youtubeId: "WdS4Z5Kfjgw",
  },
  {
    id: 83,
    name: "Daredevil",
    query: "daredevil theme",
    year: 2015,
    genre: "Action",
    youtubeId: "KFYFh8w4758",
  },
  {
    id: 84,
    name: "Arrow",
    query: "arrow theme",
    year: 2012,
    genre: "Action",
    youtubeId: "0ZO_W2YemD8",
  },
  {
    id: 85,
    name: "The Flash",
    query: "flash theme",
    year: 2014,
    genre: "Action",
    youtubeId: "ZFtlMX-7cI4",
  },
  {
    id: 86,
    name: "Supernatural",
    query: "supernatural theme carry on wayward son",
    year: 2005,
    genre: "Fantasy",
    youtubeId: "Q-ejz2RmueE",
  },
  {
    id: 87,
    name: "Sherlock",
    query: "sherlock theme",
    year: 2010,
    genre: "Mystery",
    youtubeId: "uzyKkKB7mT4",
  },
  {
    id: 88,
    name: "Jessica Jones",
    query: "jessica jones theme",
    year: 2015,
    genre: "Action",
    youtubeId: "SL_DlSxmRkA",
  },
  {
    id: 89,
    name: "Luke Cage",
    query: "luke cage theme",
    year: 2016,
    genre: "Action",
    youtubeId: "eblwtxEgCjg",
  },
  {
    id: 90,
    name: "Iron Fist",
    query: "iron fist theme",
    year: 2017,
    genre: "Action",
    youtubeId: "M9GOW97NA4g",
  },

  // === DIVERS ===
  {
    id: 91,
    name: "Gossip Girl",
    query: "gossip girl theme",
    year: 2007,
    genre: "Drama",
    youtubeId: "6C6fdZYefe0",
  },
  {
    id: 92,
    name: "Glee",
    query: "glee theme dont stop believin",
    year: 2009,
    genre: "Musical",
    youtubeId: "1FaJshIWdpU",
  },
  {
    id: 93,
    name: "Grey's Anatomy",
    query: "greys anatomy theme",
    year: 2005,
    genre: "Drama",
    youtubeId: "EGbg7-LBWak",
  },
  {
    id: 94,
    name: "House",
    query: "house theme teardrop",
    year: 2004,
    genre: "Drama",
    youtubeId: "ovU4ESybz-U",
  },
  {
    id: 95,
    name: "24",
    query: "24 theme",
    year: 2001,
    genre: "Action",
    youtubeId: "1N8xLvTaO8o",
  },
  {
    id: 96,
    name: "Prison Break",
    query: "prison break theme",
    year: 2005,
    genre: "Action",
    youtubeId: "aXBVoZ48fRc",
  },
  {
    id: 97,
    name: "Suits",
    query: "suits theme greenback boogie",
    year: 2011,
    genre: "Drama",
    youtubeId: "PhJnpbicLnk",
  },
  {
    id: 98,
    name: "White Collar",
    query: "white collar theme",
    year: 2009,
    genre: "Crime",
    youtubeId: "RIZ-nT5Ve4w",
  },
  {
    id: 99,
    name: "Burn Notice",
    query: "burn notice theme",
    year: 2007,
    genre: "Action",
    youtubeId: "N18OdEMXyP0",
  },
  {
    id: 100,
    name: "Chuck",
    query: "chuck theme short skirt long jacket",
    year: 2007,
    genre: "Action",
    youtubeId: "RhfGQnDBQX8",
  },

  // === CLASSIQUES 90s / DÉBUT 2000 ===
  {
    id: 101,
    name: "The X-Files",
    query: "x files theme",
    year: 1993,
    genre: "Sci-Fi",
    youtubeId: "hAAlDoAtV7Y",
  },
  {
    id: 102,
    name: "Twin Peaks",
    query: "twin peaks theme",
    year: 1990,
    genre: "Mystery",
    youtubeId: "nCn3LYqCnrk",
  },
  {
    id: 103,
    name: "Buffy the Vampire Slayer",
    query: "buffy theme",
    year: 1997,
    genre: "Fantasy",
    youtubeId: "5-xnvdtuRRo",
  },
  {
    id: 105,
    name: "Charmed",
    query: "charmed theme",
    year: 1998,
    genre: "Fantasy",
    youtubeId: "vQEpTXFGNgE",
  },
  {
    id: 106,
    name: "Dawson's Creek",
    query: "dawsons creek theme",
    year: 1998,
    genre: "Drama",
    youtubeId: "L_dVEtLPdDE",
  },
  {
    id: 107,
    name: "Felicity",
    query: "felicity theme",
    year: 1998,
    genre: "Drama",
    youtubeId: "pifm2nBvzKA",
  },
  {
    id: 108,
    name: "ER",
    query: "er theme",
    year: 1994,
    genre: "Drama",
    youtubeId: "Dp2EfS8FpUI",
  },
  {
    id: 109,
    name: "NYPD Blue",
    query: "nypd blue theme",
    year: 1993,
    genre: "Crime",
    youtubeId: "67unxzNCzLQ",
  },
  {
    id: 110,
    name: "Homicide: Life on the Street",
    query: "homicide life on the street theme",
    year: 1993,
    genre: "Crime",
    youtubeId: "LH3J_3hSuio",
  },
  {
    id: 111,
    name: "Oz",
    query: "oz hbo theme",
    year: 1997,
    genre: "Crime",
    youtubeId: "K7w49aAaweA",
  },
  {
    id: 112,
    name: "The Practice",
    query: "the practice theme",
    year: 1997,
    genre: "Drama",
    youtubeId: "Uvx-6OOAz8k",
  },
  {
    id: 114,
    name: "Six Feet Under",
    query: "six feet under theme",
    year: 2001,
    genre: "Drama",
    youtubeId: "Z4COQJuo7XU",
  },
  {
    id: 115,
    name: "That '70s Show",
    query: "that 70s show theme",
    year: 1998,
    genre: "Comedy",
    youtubeId: "Uply9BUShPw",
  },
  {
    id: 116,
    name: "Malcolm in the Middle",
    query: "malcolm in the middle theme",
    year: 2000,
    genre: "Comedy",
    youtubeId: "x5Za8HggalY",
  },
  {
    id: 117,
    name: "Everybody Loves Raymond",
    query: "everybody loves raymond theme",
    year: 1996,
    genre: "Comedy",
    youtubeId: "5T2_Hwj2JDg",
  },
  {
    id: 118,
    name: "Frasier",
    query: "frasier theme",
    year: 1993,
    genre: "Comedy",
    youtubeId: "0DeQDv7P3QY",
  },
  {
    id: 119,
    name: "Will & Grace",
    query: "will and grace theme",
    year: 1998,
    genre: "Comedy",
    youtubeId: "iPcJkoDOago",
  },
  {
    id: 120,
    name: "3rd Rock from the Sun",
    query: "3rd rock from the sun theme",
    year: 1996,
    genre: "Comedy",
    youtubeId: "iRqhRGfUahQ",
  },
  {
    id: 121,
    name: "Stargate SG-1",
    query: "stargate sg1 theme",
    year: 1997,
    genre: "Sci-Fi",
    youtubeId: "MnFQlVT2UBo",
  },
  {
    id: 122,
    name: "Sliders",
    query: "sliders theme",
    year: 1995,
    genre: "Sci-Fi",
    youtubeId: "u1G1pts7nMg",
  },
  {
    id: 123,
    name: "Babylon 5",
    query: "babylon 5 theme",
    year: 1994,
    genre: "Sci-Fi",
    youtubeId: "BtrUhIuEqdY",
  },
  {
    id: 124,
    name: "Farscape",
    query: "farscape theme",
    year: 1999,
    genre: "Sci-Fi",
    youtubeId: "MpRRB6q8hxc",
  },
  {
    id: 126,
    name: "Smallville",
    query: "smallville theme save me",
    year: 2001,
    genre: "Fantasy",
    youtubeId: "6W_0E1QRx84",
  },
  {
    id: 127,
    name: "Roswell",
    query: "roswell theme",
    year: 1999,
    genre: "Sci-Fi",
    youtubeId: "IixdqPQmhwQ",
  },
  {
    id: 128,
    name: "Alias",
    query: "alias theme",
    year: 2001,
    genre: "Action",
    youtubeId: "U-CtlW5J8EM",
  },
  {
    id: 129,
    name: "24",
    query: "24 theme",
    year: 2001,
    genre: "Action",
    youtubeId: "1N8xLvTaO8o",
  },
  {
    id: 130,
    name: "Millennium",
    query: "millennium theme",
    year: 1996,
    genre: "Thriller",
    youtubeId: "50kfX9iSt8A",
  },
  {
    id: 131,
    name: "Walker, Texas Ranger",
    query: "walker texas ranger theme",
    year: 1993,
    genre: "Action",
    youtubeId: "NIYZVSElmj4",
  },
  {
    id: 132,
    name: "The Shield",
    query: "the shield theme",
    year: 2002,
    genre: "Crime",
    youtubeId: "AiHECnWxq7s",
  },
  {
    id: 133,
    name: "CSI: Crime Scene Investigation",
    query: "csi theme who are you",
    year: 2000,
    genre: "Crime",
    youtubeId: "2ysZk_KMXUE",
  },
  {
    id: 134,
    name: "Law & Order",
    query: "law and order theme",
    year: 1990,
    genre: "Crime",
    youtubeId: "xz4-aEGvqQM",
  },
  {
    id: 135,
    name: "Law & Order: SVU",
    query: "law and order svu theme",
    year: 1999,
    genre: "Crime",
    youtubeId: "IRXNVdiqMuU",
  },
  {
    id: 136,
    name: "Cold Case",
    query: "cold case theme",
    year: 2003,
    genre: "Crime",
    youtubeId: "a6EEAse3i18",
  },
  {
    id: 137,
    name: "Without a Trace",
    query: "without a trace theme",
    year: 2002,
    genre: "Crime",
    youtubeId: "lSgciB53Y-w",
  },
  {
    id: 138,
    name: "Profiler",
    query: "profiler theme",
    year: 1996,
    genre: "Crime",
    youtubeId: "jOWjR9_lPtM",
  },
  {
    id: 139,
    name: "The Pretender",
    query: "the pretender theme",
    year: 1996,
    genre: "Drama",
    youtubeId: "iI9C-zMwWZE",
  },
  {
    id: 140,
    name: "Quantum Leap",
    query: "quantum leap theme",
    year: 1989,
    genre: "Sci-Fi",
    youtubeId: "DjK9GJMBpt0",
  },
  {
    id: 141,
    name: "Hercules: The Legendary Journeys",
    query: "hercules legendary journeys theme",
    year: 1995,
    genre: "Fantasy",
    youtubeId: "FFdSrgB7lqw",
  },
  {
    id: 142,
    name: "Xena: Warrior Princess",
    query: "xena warrior princess theme",
    year: 1995,
    genre: "Fantasy",
    youtubeId: "GdTnm6QNzeE",
  },
  {
    id: 143,
    name: "SeaQuest DSV",
    query: "seaquest dsv theme",
    year: 1993,
    genre: "Sci-Fi",
    youtubeId: "Gg6AsKsPH24",
  },
  {
    id: 144,
    name: "Highlander: The Series",
    query: "Queen - Princes Of The Universe ( Duncan MacLeod Tribute )",
    year: 1992,
    genre: "Fantasy",
    youtubeId: "jTuntEPJZow",
  },
  {
    id: 145,
    name: "La Femme Nikita",
    query: "la femme nikita theme",
    year: 1997,
    genre: "Action",
    youtubeId: "zDpQ3ez9P-I",
  },
  {
    id: 147,
    name: "The Outer Limits",
    query: "outer limits theme",
    year: 1995,
    genre: "Sci-Fi",
    youtubeId: "hlNMDsJlMQ0",
  },
  {
    id: 148,
    name: "Touched by an Angel",
    query: "touched by an angel theme",
    year: 1994,
    genre: "Drama",
    youtubeId: "gm7DFnOGGvY",
  },
  {
    id: 149,
    name: "Party of Five",
    query: "party of five theme",
    year: 1994,
    genre: "Drama",
    youtubeId: "mpv8prvZufk",
  },
  {
    id: 150,
    name: "My So-Called Life",
    query: "my so called life theme",
    year: 1994,
    genre: "Drama",
    youtubeId: "znVBqSI4ghQ",
  },
  {
    id: 151,
    name: "K2000",
    query: "k2000 knight rider theme",
    year: 1982,
    genre: "Action",
    youtubeId: "5BsFnk83NMI",
  },
  {
    id: 152,
    name: "Au-delà du Réèl",
    query: "au-delà du réèl generique",
    year: 1982,
    genre: "Action",
    youtubeId: "pQHbr664Z6c",
  },
];
